# docker-compose.yml file
version: "3.5"
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    volumes:
      - "./jaeger-ui.json:/etc/jaeger/jaeger-ui.json"
      - "/mnt/extension/jaeger_data:/badger"
    command: --query.ui-config /etc/jaeger/jaeger-ui.json
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - SPAN_STORAGE_TYPE=badger
      - BADGER_EPHEMERAL=false
      - BADGER_DIRECTORY_VALUE=/badger/data
      - BADGER_DIRECTORY_KEY=/badger/key
      - BADGER_SPAN_STORE_TTL=172800000000000
    ports:
      - "4317:4317"
      - "4318:4318"
      - "14250:14250"
      - "14268:14268"
      - "6831:6831/udp"
      - "6686:16686"
      - "6685:16685"
    restart: no
    deploy:
      resources:
        limits:
          memory: 40G
volumes:
  badger_data:

  docker run --rm -it -v${PWD}:${PWD} -w${PWD} \
    jaegertracing/protobuf:latest --proto_path=${PWD} \
    -I/usr/include/github.com/gogo/protobuf \
    --python_out=${PWD}/python_out proto/api_v2/model.proto