services:
  event-formation:
    deploy:
      mode: replicated
      replicas: 1
    image: supermusr-trace-to-events
    environment:
      - RUST_LOG=${RUST_LOG}
    command:
     - --broker=${BROKER}
     - --group=${GROUP_EVENT_FORMATION}
     - --trace-topic=${TRACE_TOPIC}
     - --event-topic=${DAT_EVENT_TOPIC}
     - --observability-address=${OBSV_ADDRESS_EVENT_FORMATION}
     - --otel-endpoint=${OTEL_ENDPOINT}
     - --otel-level=${OTEL_LEVEL_EVENT_FORMATION}
     - --polarity=${TTE_POLARITY}
     - --baseline=${TTE_BASELINE}
     - --otel-pipeline-tag ${PIPELINE_NAME}
     - ${TTE_INPUT_MODE}

  frame-aggregation:
    deploy:
      mode: replicated
      replicas: 1
    image: supermusr-digitiser-aggregator
    environment:
      - RUST_LOG=${RUST_LOG}
    command:
     - --broker=${BROKER}
     - --group=${GROUP_AGGREGATOR}
     - --observability-address=${OBSV_ADDRESS_AGGREGATOR}
     - --input-topic=${DAT_EVENT_TOPIC}
     - --output-topic=${FRAME_EVENT_TOPIC}
     - --otel-endpoint=${OTEL_ENDPOINT}
     - --otel-level=${OTEL_LEVEL_AGGREGATOR}
     - --frame-ttl-ms=${FRAME_TTL_MS}
     - --digitiser-ids=${DIGITISERS}

  nexus-writer:
    deploy:
      mode: replicated
      replicas: 1
    image: supermusr-nexus-writer
    environment:
      - RUST_LOG=${g_RUST_LOG}
    command:
     - --broker=${BROKER}
     - --consumer-group=${GROUP_WRITER}
     - --observability-address=${OBSV_ADDRESS_WRITER}
     - --frame-event-topic=${FRAME_EVENT_TOPIC}
     - --control-topic=${CONTROL_TOPIC}
     - --log-topic=${LOGDATA_TOPIC}
     - --sample-env-topic=${SELOG_TOPIC}
     - --alarm-topic=${ALARM_TOPIC}
     - --cache-run-ttl-ms=${RUN_TTL_MS}
     - --otel-endpoint=${OTEL_ENDPOINT}
     - --otel-level=${OTEL_LEVEL_WRITER}
     - --file-name=local
     - --archive-name=archive
    volumes:
      - ${NEXUS_OUTPUT_PATH}:/local
      - ${NEXUS_ARCHIVE_PATH}:/archive

  simulator:
    deploy:
      mode: replicated
      replicas: 1
    image: supermusr-simulator
    environment:
      - RUST_LOG=${g_RUST_LOG}
    command:
     - --broker $BROKER
     - --otel-namespace=$PIPELINE_NAME
     - --observability-address=${OBSV_ADDRESS_SIM}
     - --otel-endpoint=${OTEL_ENDPOINT}
     - ${OTEL_LEVEL_SIM}
     - defined "/home/${SIMULATOR_SOURCE}"
     - --digitiser-trace-topic=${TRACE_TOPIC}
     - --digitiser-event-topic=${DAT_EVENT_TOPIC}
     - --frame-event-topic=${FRAME_EVENT_TOPIC}
     - --control-topic=${CONTROL_TOPIC}
     - --runlog-topic=${LOGDATA_TOPIC}
     - --selog-topic=${SELOG_TOPIC}
     - --alarm-topic=${ALARM_TOPIC}
    volumes:
      - ${SIMULATOR_PATH}:/home
    depends-on:
     - event-formation
     - frame-aggregation
     - nexus-writer