services:
  event-formation:
    profiles:
      - event-formation-only
      - all
    deploy:
      mode: replicated
      replicas: 1
    image: supermusr-nexus-writer:latest
    environment:
      - RUST_LOG=info,trace_to_events=info,digitiser_aggregator=info,nexus_writer=info,simulator=info,tonic=off,h2=off,tokio_util=off,tower=off,hyper=off
      - NO_COLOR=true
      - OTEL_LEVEL=info,trace_to_events=info,trace_to_events::channels=info,trace_to_events::pulse_detection=warn,digitiser_aggregator=info,nexus_writer=info,simulator=info
    ports:
      - 127.0.0.1:29090:9090
    command: [--broker,localhost:19092,--consumer-group,trace_to_events,--observability-address,127.0.0.1:29090,--trace-topic,Traces,--event-topic,Events,--polarity,positive,--baseline,0,--otel-endpoint,http://172.16.105.83:4317/v1/traces,--otel-namespace,local,differential-threshold-discriminator,--begin-threshold,5,--end-threshold,0,--begin-duration,2,--end-duration,0,--cool-off,0,--peak-height-mode,value-at-end-trigger,--peak-height-basis,trace-baseline]
    network_mode: "host"
    #extra_hosts:
    #  - "host.docker.internal:host-gateway"

  frame-aggregation:
    profiles:
      - frame-aggregation-only
      - all-but-trace-to-events
      - all
    deploy:
      mode: replicated
      replicas: 1
    image: supermusr-digitiser-aggregator:latest
    environment:
      - RUST_LOG=info,trace_to_events=info,digitiser_aggregator=info,nexus_writer=info,simulator=info,tonic=off,h2=off,tokio_util=off,tower=off,hyper=off
      - NO_COLOR=true
      - OTEL_LEVEL=info,trace_to_events=info,trace_to_events::channels=info,trace_to_events::pulse_detection=warn,digitiser_aggregator=info,nexus_writer=info,simulator=info
    ports:
      - 127.0.0.1:29091:9090
    command: [--broker,localhost:19092,--group,digitiser_aggregator,--observability-address,127.0.0.1:29091,--input-topic,Events,--output-topic,FrameEvents,--frame-ttl-ms,3500,--send-frame-buffer-size,4000,--otel-endpoint,http://172.16.105.83:4317/v1/traces,--otel-namespace,local,-d0,1,2,3,4,5,6,7]
    network_mode: "host"
    #extra_hosts:
    #  - "host.docker.internal:host-gateway"

  nexus-writer:
    profiles:
     - nexus-writer-only
     - all-but-trace-to-events
     - all
    deploy:
      mode: replicated
      replicas: 1
    image: supermusr-nexus-writer:latest
    environment:
      - RUST_LOG=info,trace_to_events=info,digitiser_aggregator=info,nexus_writer=info,simulator=info,tonic=off,h2=off,tokio_util=off,tower=off,hyper=off
      - NO_COLOR=true
      - OTEL_LEVEL=info,trace_to_events=info,trace_to_events::channels=info,trace_to_events::pulse_detection=warn,digitiser_aggregator=info,nexus_writer=info,simulator=info
    ports:
      - 127.0.0.1:29092:9090
    command: [--broker,localhost:19092,--consumer-group,nexus_writer,--observability-address,127.0.0.1:29092,--control-topic,Controls,--frame-event-topic,FrameEvents,--log-topic,Logs,--sample-env-topic,SELogs,--alarm-topic,Alarms,--cache-run-ttl-ms,9000,--otel-endpoint,http://172.16.105.83:4317/v1/traces,--otel-namespace,local,--local-path,Output/local,--archive-path,archive/incoming/local]
    volumes:
      - ../:/local
      - ../:/archive
    network_mode: "host"
    #extra_hosts:
    #  - "host.docker.internal:host-gateway"

  event-formation-one:
    profiles:
      - event-formation-test
    deploy:
      mode: replicated
      replicas: 1
    image: 
    environment:
      - RUST_LOG=info,trace_to_events=info,digitiser_aggregator=info,nexus_writer=info,simulator=info,tonic=off,h2=off,tokio_util=off,tower=off,hyper=off
      - NO_COLOR=true
      - OTEL_LEVEL=info,trace_to_events=info,trace_to_events::channels=info,trace_to_events::pulse_detection=warn,digitiser_aggregator=info,nexus_writer=info,simulator=info
    ports:
      - 127.0.0.1:29090:9090
    command:
      - --broker=
      - --consumer-group=-one
      - --trace-topic=
      - --event-topic=-one
      - --observability-address=127.0.0.1:29091
      - --otel-endpoint=
      - --polarity=
      - --baseline=
      - --otel-namespace=-one
      - fixed-threshold-discriminator
      - --threshold=2200
      - --duration=1
      - --cool-off=0
    network_mode: "host"

  event-formation-two:
    profiles:
      - event-formation-test
    deploy:
      mode: replicated
      replicas: 1
    image: 
    environment:
      - RUST_LOG=info,trace_to_events=info,digitiser_aggregator=info,nexus_writer=info,simulator=info,tonic=off,h2=off,tokio_util=off,tower=off,hyper=off
      - NO_COLOR=true
      - OTEL_LEVEL=info,trace_to_events=info,trace_to_events::channels=info,trace_to_events::pulse_detection=warn,digitiser_aggregator=info,nexus_writer=info,simulator=info
    ports:
      - 127.0.0.1:29090:9090
    command:
      - --broker=
      - --consumer-group=-two
      - --trace-topic=
      - --event-topic=-two
      - --observability-address=127.0.0.1:29092
      - --otel-endpoint=
      - --polarity=
      - --baseline=
      - --otel-namespace=-two
      - differential-threshold-discriminator
      - --threshold=5
      - --duration=1
      - --cool-off=0
    network_mode: "host"
    #extra_hosts:
    #  - "host.docker.internal:host-gateway"