services:
  event-formation:
    profiles:
      - main
      - main-and-test-event-formation
      - main-and-test-digitiser-aggregator
      - main-and-test-nexus-writer
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 500m
    restart: on-failure
    logging:
      options:
        path: /home/dankirk/pipeline-test/archive/incoming/hifi_test/logs/event-formation.log
    image: ghcr.io/stfc-icd-research-and-design/supermusr-trace-to-events:main
    environment:
      - RUST_LOG=info,digitiser_aggregator=info,nexus_writer=info,trace_to_events=warn,
      - NO_COLOR=true
      - OTEL_LEVEL=none,digitiser_aggregator=info,nexus_writer=info,trace_to_events=info,trace_to_events::channels=warn,trace_to_events::pulse_detection=warn
    command:
      - --broker=130.246.55.29:9092
      - --consumer-group=trace-to-events-test
      - --trace-topic=daq-traces-in
      - --event-topic=daq-events-test
      - --observability-address=127.0.0.1:29090
      - --otel-endpoint=http://172.16.105.83:4317/v1/traces
      - --otel-namespace=hifi_test
      - --polarity=positive
      - --baseline=0
      - fixed-threshold-discriminator
      - --threshold=2100
      - --duration=1
      - --cool-off=0

  frame-aggregation:
    profiles:
      - main
      - main-and-test-event-formation
      - main-and-test-digitiser-aggregator
      - main-and-test-nexus-writer
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 500m
    restart: on-failure
    logging:
      options:
        path: /home/dankirk/pipeline-test/archive/incoming/hifi_test/logs/digitiser-aggregator.log
    image: ghcr.io/stfc-icd-research-and-design/supermusr-digitiser-aggregator:main
    environment:
      - RUST_LOG=info,digitiser_aggregator=info,nexus_writer=info,trace_to_events=warn,
      - NO_COLOR=true
      - OTEL_LEVEL=none,digitiser_aggregator=info,nexus_writer=info,trace_to_events=info,trace_to_events::channels=warn,trace_to_events::pulse_detection=warn
    command:
      - --broker=130.246.55.29:9092
      - --group=digitiser-aggregator-test
      - --observability-address=127.0.0.1:29091
      - --input-topic=daq-events-test
      - --output-topic=frame-events-test
      - --otel-endpoint=http://172.16.105.83:4317/v1/traces
      - --otel-namespace=hifi_test
      - --frame-ttl-ms=200
      - -d4,5,6,7,8,9,10,11

  nexus-writer:
    profiles:
      - main
      - main-and-test-event-formation
      - main-and-test-digitiser-aggregator
      - main-and-test-nexus-writer
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 350m
    restart: on-failure
    logging:
      options:
        path: /home/dankirk/pipeline-test/archive/incoming/hifi_test/logs/nexus-writer.log
    image: localhost/supermusr-nexus-writer:latest
#    image: ghcr.io/stfc-icd-research-and-design/supermusr-nexus-writer:main
    environment:
      - RUST_LOG=info,digitiser_aggregator=info,nexus_writer=info,trace_to_events=warn,
      - NO_COLOR=true
      - OTEL_LEVEL=none,digitiser_aggregator=info,nexus_writer=info,trace_to_events=info,trace_to_events::channels=warn,trace_to_events::pulse_detection=warn
    command:
      - --broker=130.246.55.29:9092
      - --consumer-group=nexus-writer-test
      - --observability-address=127.0.0.1:29092
      - --frame-event-topic=frame-events-test
      - --control-topic=ics-control-change
      - --log-topic=ics-metadata
      - --sample-env-topic=HIFI_sampleEnv
      - --alarm-topic=ics-alarms
      - --cache-run-ttl-ms=2500
      - --event-list-chunk-size=16384
      - --otel-endpoint=http://172.16.105.83:4317/v1/traces
      - --otel-namespace=hifi_test
      - --configuration-options=broker_settings:{broker:'130.246.55.29:9092', trace_to_events_group:'trace-to-events-test', digitiser_aggregator_group:'digitiser-aggregator-test', nexus_writer_group:'nexus-writer-test'}, topics:{trace:'daq-traces-in', dat_eventlists:'daq-events-test', frame_eventlist:'frame-events-test', control:'ics-control-change', logs:'ics-metadata', selogs:'HIFI_sampleEnv', alarms:'ics-alarms'}, event_formation:{polarity:'positive', baseline:0, input-mode:'fixed-threshold-discriminator', threshold:2100, duration:1, cooloff:0}, digitiser_aggregator:{digitisers:'-d4,5,6,7,8,9,10,11', frame_ttl_ms:200}, nexus_writer:{local_host_path:'./Output/Local_test', archive_host_path:'./archive/incoming/hifi_test', run_ttl_ms:2500}
      - --local-path=/local
      - --archive-path=/archive
    volumes:
      - .././Output/Local_test/:/local/
      - .././archive/incoming/hifi_test/:/archive/

  nexus-writer-test:
    profiles:
      - main-and-test-nexus-writer
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 350m
    restart: on-failure
    logging:
      options:
        path: /home/dankirk/pipeline-test/archive/incoming/hifi_test/logs/nexus-writer.log
    image: localhost/supermusr-nexus-writer
    environment:
      - RUST_LOG=info,digitiser_aggregator=info,nexus_writer=info,trace_to_events=warn,
      - NO_COLOR=true
      - OTEL_LEVEL=none,digitiser_aggregator=info,nexus_writer=info,trace_to_events=info,trace_to_events::channels=warn,trace_to_events::pulse_detection=warn
    command:
      - --broker=130.246.55.29:9092
      - --consumer-group=nexus-writer-test
      - --observability-address=127.0.0.1:29092
      - --frame-event-topic=frame-events-test
      - --control-topic=ics-control-change
      - --log-topic=ics-metadata
      - --sample-env-topic=HIFI_sampleEnv
      - --alarm-topic=ics-alarms
      - --cache-run-ttl-ms=2500
      - --event-list-chunk-size=16384
      - --otel-endpoint=http://172.16.105.83:4317/v1/traces
      - --otel-namespace=hifi-test
      - --local-path=local
      - --archive-path=archive
    volumes:
      - ../Output/Local_test:/local
      - ../archive/incoming/hifi_test:/archive
      - ../archive/incoming/hifi_test/logs:/logs