services:
  event-formation:
    profiles:
      - event-formation-only
      - all
    deploy:
      mode: replicated
      replicas: 1
    image: $IMAGE_EVENT_FORMATION
    environment:
      - RUST_LOG=${RUST_LOG}
      - NO_COLOR=${NO_COLOR}
      - OTEL_LEVEL=${OTEL_LEVEL}
    ports:
      - ${OBSV_ADDRESS_EVENT_FORMATION}:9090
    command: ${EVENT_FORMATION_ARGS}
    network_mode: "host"
    #extra_hosts:
    #  - "host.docker.internal:host-gateway"

  frame-aggregation:
    profiles:
      - frame-aggregation-only
      - all-but-trace-to-events
      - all
    deploy:
      mode: replicated
      replicas: 1
    image: $IMAGE_AGGREGATOR
    environment:
      - RUST_LOG=${RUST_LOG}
      - NO_COLOR=${NO_COLOR}
      - OTEL_LEVEL=${OTEL_LEVEL}
    ports:
      - ${OBSV_ADDRESS_AGGREGATOR}:9090
    command: $AGGREGATOR_ARGS
    network_mode: "host"
    #extra_hosts:
    #  - "host.docker.internal:host-gateway"

  nexus-writer:
    profiles:
     - nexus-writer-only
     - all-but-trace-to-events
     - all
    deploy:
      mode: replicated
      replicas: 1
    image: $IMAGE_WRITER
    environment:
      - RUST_LOG=${RUST_LOG}
      - NO_COLOR=${NO_COLOR}
      - OTEL_LEVEL=${OTEL_LEVEL}
    ports:
      - ${OBSV_ADDRESS_WRITER}:9090
    command: $WRITER_ARGS
    volumes:
      - ../${NEXUS_OUTPUT_PATH}:/local
      - ../${NEXUS_ARCHIVE_PATH}:/archive
    network_mode: "host"
    #extra_hosts:
    #  - "host.docker.internal:host-gateway"
