services:
  event-formation:
    profiles:
      - event-formation-only
      - all
    network_mode: "host"
    deploy:
      mode: replicated
      replicas: 1
    image: ghcr.io/stfc-icd-research-and-design/supermusr-trace-to-events:main
    environment:
      - RUST_LOG=info,digitiser_aggregator=info,nexus_writer=info,trace_to_events=warn,tonic=off,h2=off,tokio_util=off,tower=off,hyper=off
      - NO_COLOR=true
      - OTEL_LEVEL=info,simulator=info,digitiser_aggregator=info,nexus_writer=info,trace_to_events=info,trace_to_events::channels=warn,trace_to_events::pulse_detection=warn
    command:
      - --broker=130.246.55.29:9092
      - --consumer-group=trace-to-events-test
      - --trace-topic=daq-traces-in
      - --event-topic=daq-events
      - --observability-address=127.0.0.1:29090
      - --otel-endpoint=--otel-endpoint http://localhost:4317/v1/traces
      - --polarity=positive
      - --baseline=0
      - --otel-namespace=localtest
      - fixed-threshold-discriminator
      - --threshold=10
      - --duration=1
      - --cool-off=0

  frame-aggregation:
    profiles:
      - frame-aggregation-only
      - all
    deploy:
      mode: replicated
      replicas: 1
    image: ghcr.io/stfc-icd-research-and-design/supermusr-digitiser-aggregator:main
    network_mode: "host"
    environment:
      - RUST_LOG=info,digitiser_aggregator=info,nexus_writer=info,trace_to_events=warn,tonic=off,h2=off,tokio_util=off,tower=off,hyper=off
      - NO_COLOR=true
      - OTEL_LEVEL=info,simulator=info,digitiser_aggregator=info,nexus_writer=info,trace_to_events=info,trace_to_events::channels=warn,trace_to_events::pulse_detection=warn
    command:
      - --broker=130.246.55.29:9092
      - --group=digitiser-aggregator-test
      - --observability-address=127.0.0.1:29091
      - --input-topic=daq-events
      - --output-topic=frame-events
      - --otel-endpoint=--otel-endpoint http://localhost:4317/v1/traces
      - --otel-namespace=localtest
      - --frame-ttl-ms=5000
      - -d4,5,6,7,8,9,10,11

  nexus-writer:
    profiles:
     - nexus-writer-only
     - all
    deploy:
      mode: replicated
      replicas: 1
    image: supermusr-nexus-writer:latest
    network_mode: "host"
    environment:
      - RUST_LOG=info,digitiser_aggregator=info,nexus_writer=info,trace_to_events=warn,tonic=off,h2=off,tokio_util=off,tower=off,hyper=off
      - NO_COLOR=true
      - OTEL_LEVEL=info,simulator=info,digitiser_aggregator=info,nexus_writer=info,trace_to_events=info,trace_to_events::channels=warn,trace_to_events::pulse_detection=warn
    command:
      - --broker=130.246.55.29:9092
      - --consumer-group=nexus-writer-test
      - --observability-address=127.0.0.1:29092
      - --frame-event-topic=frame-events
      - --control-topic=ics-control-change
      - --log-topic=ics-metadata
      - --sample-env-topic=HIFI_sampleEnv
      - --alarm-topic=ics-alarms
      - --cache-run-ttl-ms=500
      - --otel-endpoint=--otel-endpoint http://localhost:4317/v1/traces
      - --otel-namespace=localtest
      - --file-name=local
      - --archive-name=archive
    volumes:
      - ../Output/HiFi_test:/local
      - ../archive/incoming/hifi-via-local_test:/archive