services:
  simulator:
    deploy:
      mode: replicated
      replicas: 1
    network_mode: "host"
    image: supermusr-simulator:latest
    environment:
      - RUST_LOG=info,digitiser_aggregator=info,nexus_writer=info,trace_to_events=info,tonic=off,h2=off,tokio_util=off,tower=off,hyper=off
      - MAX_DIGITISER=7
      - NUM_DIGITISERS=8
      - RUN_NAME=ShortTest
      - NO_COLOR=true
      - OTEL_LEVEL=info,simulator=off,digitiser_aggregator=info,nexus_writer=info,trace_to_events=info,trace_to_events::channels=warn,trace_to_events::pulse_detection=warn
    command:
     - --broker=localhost:19092
     - --otel-namespace=TEST_011TEST_011
     - --otel-endpoint=http://172.16.105.83:4317/v1/traces
     - defined
     - "/home/Benchmarks/timing.json"
     - --digitiser-trace-topic=Traces
     - --digitiser-event-topic=Events
     - --frame-event-topic=FrameEvents
     - --control-topic=Controls
     - --runlog-topic=Logs
     - --selog-topic=SELogs
     - --alarm-topic=Alarms
    volumes:
      - ../Simulations:/home
    #extra_hosts:
    #  - "host.docker.internal:host-gateway"