services:
  simulator:
    deploy:
      mode: replicated
      replicas: 1
    image: ghcr.io/stfc-icd-research-and-design/supermusr-simulator:main
    environment:
      - RUST_LOG=${RUST_LOG}
      - MAX_DIGITISER=${MAX_DIGITISER}
      - NUM_DIGITISERS=${NUM_DIGITISERS}
      - RUN_NAME=${RUN_NAME}
    command:
     - --broker=${BROKER}
     - --otel-namespace=${PIPELINE_NAME}
     - --otel-endpoint=${OTEL_ENDPOINT}
     - ${OTEL_LEVEL_SIM}
     - defined
     - "/home/${SIMULATOR_SOURCE}"
     - --digitiser-trace-topic=${TRACE_TOPIC}
     - --digitiser-event-topic=${DAT_EVENT_TOPIC}
     - --frame-event-topic=${FRAME_EVENT_TOPIC}
     - --control-topic=${CONTROL_TOPIC}
     - --runlog-topic=${LOGS_TOPIC}
     - --selog-topic=${SELOGS_TOPIC}
     - --alarm-topic=${ALARMS_TOPIC}
    volumes:
      - ../${SIMULATOR_PATH}:/home