services:
  simulator:
    deploy:
      mode: replicated
      replicas: 1
    network_mode: "host"
    image: ${IMAGE_SIMULATOR}
    environment:
      - RUST_LOG=${RUST_LOG}
      - LAST_DIGITISER=${MAX_DIGITISER}
      - NUM_DIGITISERS=${NUM_DIGITISERS}
      - RUN_NAME=${RUN_NAME}
      - NO_COLOR=${NO_COLOR}
      - OTEL_LEVEL=${OTEL_LEVEL}
    command: $SIMULATOR_ARGS
    volumes:
      - type: bind
        source: ../$SOURCE_FILE
        target: /app/source.json
        read_only: true
    #extra_hosts:
    #  - "host.docker.internal:host-gateway"