#g_TTE_INPUT_MODE="advanced-muon-detector --muon-onset=0.1 --muon-fall=-0.1 --muon-termination=0.01 --duration=10 --smoothing-window-size=10"
g_TTE_INPUT_MODE="fixed-threshold-discriminator"
g_TTE_INPUT_MODE="differential-threshold-discriminator"
g_TTE_BEGIN_THRESHOLD="--begin-threshold=5"
g_TTE_END_THRESHOLD="--end-threshold=0"
g_TTE_THRESHOLD="$g_TTE_BEGIN_THRESHOLD $g_TTE_END_THRESHOLD"
g_TTE_BEGIN_DURATION="--begin-duration=2"
g_TTE_END_DURATION="--end-duration=0"
g_TTE_DURATION="$g_TTE_BEGIN_DURATION $g_TTE_END_DURATION"
g_TTE_COOLOFF="--cool-off=0"
g_TTE_PEAK_MODE="--peak-height-mode=value-at-end-trigger"
g_TTE_PEAK_BASIS="--peak-height-basis=trace-baseline"
#g_TTE_INPUT_COMMAND="fixed-threshold-discriminator --threshold ${g_TTE_FTD_THRESHOLD} --duration ${g_TTE_FTD_DURATION} --cool-off ${g_TTE_FTD_COOLOFF}"
g_TTE_INPUT_COMMAND="${g_TTE_INPUT_MODE} ${g_TTE_THRESHOLD} ${g_TTE_DURATION} ${g_TTE_COOLOFF} ${g_TTE_PEAK_MODE} ${g_TTE_PEAK_BASIS}"